GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYXJ0aW56dXRlbG1hbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRmcWlqTXcubU9NQnQxazZkTTM5dlguTXVDTEQwY2F3TGd3ZTkzZVBzN08wc1UuTE53OHV3MiIsIm5hbWUiOm51bGwsImlhdCI6MTY5MzMxODcyNn0.CGVrL_OCFp6qQJRhKUlbM73C0xknAGJyLLMBfNitERo
###

POST http://localhost:3000/users
Content-Type: application/json 

{
    "email": "martinzutelman@gmail.com",
    "password": "reyderedes"
}


###

POST http://localhost:3000/users/login
Content-Type: application/json 

{
    "email": "martinzutelman@gmail.com",
    "password": "reyderedes"
}

###

<!--

{
    "email": "u3",
    "password": "06"
}

these is password wich's hashed value is hardcoded into the array in the server files, in order to test acces in both servers.
-->