GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlnbmFjaW9AZ21haWwuY29tIiwiaWF0IjoxNjkzNzY4NTYzLCJleHAiOjE2OTM3Njg1Nzh9.TkrQnIE58NsNWaV7WCrsgr8dXChKruV9MOgL0Kelr_0
###

POST http://localhost:3000/users
Content-Type: application/json 

{
    "email": "ignacio@gmail.com",
    "password": "ignacio"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJpZ25hY2lvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGowSWZ1YkZ3RzF3MXgxSjZUczNYYy5XRnZRN2dwNVZ3a0FBajFnUUdkMkJjNWJlZU1kS1RLIiwibmFtZSI6bnVsbCwiaWF0IjoxNjkzNzY3NzE0fQ.KW2lU-KwGCFnKUt4_eTRVTxZ_BEtfvJ4UpdPIZwDPhg"
} 

###

POST http://localhost:4000/users/login
Content-Type: application/json 

{
    "email": "ignacio@gmail.com",
    "password": "ignacio"
}

###

<!--

{
    "email": "u3",
    "password": "06"
}

these is password wich's hashed value is hardcoded into the array in the server files, in order to test acces in both servers.
-->